db:
  port: ${DB_PORT}
  host: ${DB_HOST}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  name: ${DB_NAME}
server:
  port: ${PORT}
  timeout: ${TIMEOUT}
external-api:
  base-url: ${BASE_URL}
  timeout: ${TIMEOUT}

