services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/.env
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
